name: "CI"
on:
  push:
    branches-ignore:
      - "production"
      - "docs"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - ".gitignore"
      - "README.md"
      - "LICENSE"
  pull_request:
    paths:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # for posts' lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1 # Set Ruby version to 3.1.1
          bundler-cache: true # Enable bundler caching

      - name: Install Bundler
        run: gem install bundler -v '~> 2.3' # Install a specific version of Bundler

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Ensure using a stable Node.js version

      - name: Install Dependencies
        run: |
          bundle install --jobs=4 --retry=3 --verbose # Install Ruby gems with verbose output
          npm install # Install Node.js packages

      - name: Debug Bundler
        run: |
          echo "Bundler version: $(bundle -v)"
          echo "Gems installed:"
          bundle list

      - name: Build Assets
        run: npm run build

      - name: Test Site
        run: bash tools/test

      - name: Build Jekyll Site
        run: |
          bundle exec jekyll build # Build the Jekyll site

      - name: Deploy Site
        run: |
          # Add your deployment command here, e.g., rsync, scp, or another method
          echo "Deployment step would go here"